@startuml
package Telnet {
    package Tx 
    package Rx 
}
package Parsing  
package Action_Service
package Player_Service
package Actions 
package Services 
package Databases 

Rx --> Parsing
Parsing --> Action_Service
Action_Service --> Player_Service
Action_Service <-- Actions
Player_Service <-- Actions
Tx <-- Services
Actions --> Services
Services --> Databases
@enduml